[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/admin/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PORT = "8000"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
